version: '3'

services:
  webserver-init:
    build: webserver-init
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - DOMAIN=thingsboard2.pavax.ch
    volumes:
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/nginx/ssl/

  certbot:
    image: certbot/certbot:latest
    depends_on:
     - webserver-init
    command: >- 
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email patrick.dobler@gmail.com --agree-tos --no-eff-email
             -d thingsboard2.pavax.ch
    volumes:
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/letsencrypt/

volumes:
    certbot_conf:
    certbot_www:
