version: '3'

services:
  nginx:
    build: webserver 
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - DOMAIN=$DOMAIN
      - EMAIL=$EMAIL
      - TARGET_URL=$TARGET_URL
    volumes:
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/nginx/ssl/

  certbot:
    image: certbot/certbot:latest
    depends_on:
     - nginx
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email $EMAIL --agree-tos --no-eff-email
             -d $DOMAIN
    volumes:
      - certbot_www:/var/www/certbot/
      - certbot_conf:/etc/letsencrypt/

volumes:
    certbot_conf:
       external: true
    certbot_www:
