version: '3'

services:
  webserver:
    build: .
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email patrick.dobler@gmail.com --agree-tos --no-eff-email -d thingsboard.pavax.ch
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw
volumes:
    nginx_conf:
    certbot_conf:
    certbot_www: